workspace:
  base: /go/src
  path: github.com/appleboy/drone-git-push

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    secrets: [ codecov_token ]
    commands:
      - make vet
      - make lint
      - make test
      - make build
      - make misspell-check
      - make test-vendor

  build_linux_amd64:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_arm

  publish_linux_amd64:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: ${DRONE_REPO}
    auto_tag: true
    group: release
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
      local: false

  publish_alpine:
    image: plugins/docker
    group: release
    pull: true
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    default_tags: true
    default_suffix: alpine
    repo: ${DRONE_REPO}
    when:
      event: [ push, tag ]
      local: false

  # publish_linux_i386:
  #   image: plugins/docker
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: release
  #   repo: ${DRONE_REPO}
  #   auto_tag: true
  #   auto_tag_suffix: i386
  #   dockerfile: Dockerfile.i386
  #   when:
  #     event: [ push, tag ]
  #     local: false

  publish_linux_arm64:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  # publish_linux_arm:
  #   image: plugins/docker
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: release
  #   repo: ${DRONE_REPO}
  #   auto_tag: true
  #   auto_tag_suffix: arm
  #   dockerfile: Dockerfile.arm
  #   when:
  #     event: [ push, tag ]
  #     local: false

  release:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ tag ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false
