build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git-push
    when:
      branch: master

notify:
  downstream:
    token: $$DOWNSTREAM_TOKEN
    repositories:
      - drone-plugins/drone-azure-web-apps
      - drone-plugins/drone-deis
      - drone-plugins/drone-heroku
      - drone-plugins/drone-scalingo
    when:
      event: push
      branch: master
      success: true

plugin:
  name: Git Push
  desc: Deploys or updates a project via Git
  type: deploy
  image: plugins/drone-git-push
  labels:
    - git
